site_name: DragonMine Z - Documentation
site_url: https://dragonminez.github.io/dragonminez-docs/
docs_dir: ../docs/

repo_url: https://github.com/DragonMineZ/dragonminez
repo_name: DragonMineZ/dragonminez
copyright: Copyright © 2024 - 2025 | DragonMine Z

theme:
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
   - navigation.instant
   - navigation.instant.progress
   - navigation.instant.preview
   - navigation.tracking
   - navigation.path
   - navigation.indexes
   - toc.follow
   - navigation.top
   - search.suggest
   - search.highlight
   - search.share
   - content.code.annotate
   - content.code.copy
   - content.code.selected

extra:
  generator: false
  homepage: https://dragonminez.com/home
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/b5MgRNb3D7
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/DragonMineZ
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@DragonMine-Z
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DragonMineZ
    - icon: fontawesome/brands/github
      link: https://github.com/DragonMineZ/dragonminez

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
          nav_translations:
            Home: Home
            About: About
            Credits: Credits
            License: License
            Support: Support
            Wiki: Wiki
            Getting Started: Getting Started
            Servers: Servers
            Server Support: Server Support
            General Config: General Config
            Racial Config: Racial Config
            Commands: Commands
            Character: Character
            Locations: Locations
            Skills: Skills
            Transformations: Transformations
            Storyline: Storyline
            Items: Items
            Blocks: Blocks
            Armors: Armors
            Entities: Entities
            Contributing: Contributing
            Translate the Mod: Translate the mod
            Translate the Docs: Translate the docs
            Other Contributions: Other Contributions
        - locale: es
          default: false
          name: Español
          build: true
          nav_translations:
            Home: Inicio
            About: Acerca de
            Credits: Créditos
            License: Licencia
            Support: Soporte
            Wiki: Wiki
            Getting Started: Guía de Inicio
            Servers: Servidores
            Server Support: Soporte para Servidores
            General Config: Configuración General
            Racial Config: Configuración Racial
            Commands: Comandos
            Character: Personaje
            Locations: Localizaciones
            Skills: Habilidades
            Transformations: Transformaciones
            Storyline: Historia
            Items: Objetos
            Blocks: Bloques
            Armors: Armaduras
            Entities: Entidades
            Contributing: Contribuciones
            Translate the Mod: Traducir el mod
            Translate the Docs: Traducir la documentación
            Other Contributions: Otras Contribuciones
        - locale: "af"
          default: false
          name: Afrikaans
          build: true
        - locale: ar
          default: false
          name: العربية
          build: true
        - locale: "ca"
          default: false
          name: Català
          build: true
        - locale: "cs"
          default: false
          name: Čeština
          build: true
        - locale: "da"
          default: false
          name: Dansk
          build: true
        - locale: "de"
          default: false
          name: Deutsch
          build: true
        - locale: "el"
          default: false
          name: Ελληνικά
          build: true
        - locale: "fi"
          default: false
          name: Suomi
          build: true
        - locale: "fr"
          default: false
          name: Français
          build: true
        - locale: "he"
          default: false
          name: עברית
          build: true
        - locale: "hu"
          default: false
          name: Magyar
          build: true
        - locale: "it"
          default: false
          name: Italiano
          build: true
        - locale: "ja"
          default: false
          name: 日本語
          build: true
        - locale: "ko"
          default: false
          name: 한국어
          build: true
        - locale: "nl"
          default: false
          name: Nederlands
          build: true
        - locale: "nb"
          default: false
          name: Norsk
          build: true
        - locale: "pl"
          default: false
          name: Polski
          build: true
        - locale: "pt"
          default: false
          name: Português
          build: true
        - locale: "ro"
          default: false
          name: Română
          build: true
        - locale: "ru"
          default: false
          name: Русский
          build: true
        - locale: "sr"
          default: false
          name: Српски
          build: true
        - locale: "sv"
          default: false
          name: Svenska
          build: true
        - locale: "tr"
          default: false
          name: Türkçe
          build: true
        - locale: "uk"
          default: false
          name: Українська
          build: true
        - locale: "vi"
          default: false
          name: Tiếng Việt
          build: true
        - locale: "zh"
          default: false
          name: 简体中文
          build: true


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - tables
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Home: index.md
  - About:
    - Credits: about/credits.md
    - License: about/license.md
    - Support: about/support.md
  - Wiki: 
    - Getting Started: wiki/gettingstarted.md
    - Servers: 
      - Server Support: wiki/servers/support.md
      - General Config: wiki/servers/generalconfig.md
      - Racial Config: wiki/servers/racialconfig.md
      - Commands: wiki/servers/commands.md
    - Character: wiki/character.md
    - Locations: wiki/locations.md
    - Skills: wiki/skills.md
    - Transformations: wiki/transformations.md
    - Storyline: wiki/storyline.md
    - Items: wiki/items.md
    - Blocks: wiki/blocks.md
    - Armors: wiki/armors.md
    - Entities: wiki/entities.md
  - Contributing:
    - Translate the Mod: contributing/translate.md
    - Translate the Docs: contributing/translatedocs.md
    - Other Contributions: contributing/othercontributions.md